# Generated by Django 4.1.6 on 2023-02-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarusel',
            name='info2',
            field=models.CharField(blank=True, max_length=15, verbose_name='HomeCarusel info2'),
        ),
    ]
