# Generated by Django 4.1.6 on 2023-02-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_homecarusel_info2'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarusel',
            name='superuser',
            field=models.ImageField(default=1, upload_to='media', verbose_name='HomeCarusel superuser image'),
            preserve_default=False,
        ),
    ]
