# Generated by Django 4.1.6 on 2023-02-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_hometopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometopic',
            name='history',
            field=models.TextField(default=1, verbose_name='HomeTopic history'),
            preserve_default=False,
        ),
    ]
