# Generated by Django 4.1.6 on 2023-02-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_hometopic_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometopic',
            name='link',
            field=models.SlugField(blank=True, unique=True, verbose_name='HomeTopic link'),
        ),
    ]
