# Generated by Django 4.1.6 on 2023-02-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_hometopic_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hometopic',
            old_name='link',
            new_name='slug',
        ),
    ]
