# Generated by Django 4.1.6 on 2023-02-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_rename_link_hometopic_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Category name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Category image')),
                ('info', models.CharField(max_length=20, verbose_name='Category info')),
            ],
        ),
    ]
