# Generated by Django 4.1.6 on 2023-02-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_homecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecategory',
            options={'verbose_name': 'HomeCategory', 'verbose_name_plural': 'HomeCategories'},
        ),
        migrations.AddField(
            model_name='hometopic',
            name='homecategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='garaje', to='pages.homecategory'),
            preserve_default=False,
        ),
    ]
